# Index constants for accessing data in the Data Handler

class CDH_IDX:
    TIME = 0
    SC_STATE = 1
    SD_USAGE = 2
    CURRENT_RAM_USAGE = 3
    REBOOT_COUNT = 4
    WATCHDOG_TIMER = 5
    HAL_BITFLAGS = 6


class EPS_IDX:
    TIME_EPS = 0
    MAINBOARD_VOLTAGE = 1
    MAINBOARD_CURRENT = 2
    BATTERY_PACK_REPORTED_SOC = 3
    BATTERY_PACK_REPORTED_CAPACITY = 4
    BATTERY_PACK_CURRENT = 5
    BATTERY_PACK_VOLTAGE = 6
    BATTERY_PACK_MIDPOINT_VOLTAGE = 7
    BATTERY_CYCLES = 8
    BATTERY_PACK_TTE = 9
    BATTERY_PACK_TTF = 10
    BATTERY_TIME_SINCE_POWER_UP = 11
    XP_COIL_VOLTAGE = 12
    XP_COIL_CURRENT = 13
    XM_COIL_VOLTAGE = 14
    XM_COIL_CURRENT = 15
    YP_COIL_VOLTAGE = 16
    YP_COIL_CURRENT = 17
    YM_COIL_VOLTAGE = 18
    YM_COIL_CURRENT = 19
    ZP_COIL_VOLTAGE = 20
    ZP_COIL_CURRENT = 21
    ZM_COIL_VOLTAGE = 22
    ZM_COIL_CURRENT = 23
    JETSON_INPUT_VOLTAGE = 24
    JETSON_INPUT_CURRENT = 25
    RF_LDO_OUTPUT_VOLTAGE = 26
    RF_LDO_OUTPUT_CURRENT = 27
    GPS_VOLTAGE = 28
    GPS_CURRENT = 29
    XP_SOLAR_CHARGE_VOLTAGE = 30
    XP_SOLAR_CHARGE_CURRENT = 31
    XM_SOLAR_CHARGE_VOLTAGE = 32
    XM_SOLAR_CHARGE_CURRENT = 33
    YP_SOLAR_CHARGE_VOLTAGE = 34
    YP_SOLAR_CHARGE_CURRENT = 35
    YM_SOLAR_CHARGE_VOLTAGE = 36
    YM_SOLAR_CHARGE_CURRENT = 37
    ZP_SOLAR_CHARGE_VOLTAGE = 38
    ZP_SOLAR_CHARGE_CURRENT = 39
    ZM_SOLAR_CHARGE_VOLTAGE = 40
    ZM_SOLAR_CHARGE_CURRENT = 41


class ADCS_IDX:
    TIME_ADCS = 0
    ADCS_STATE = 1
    GYRO_X = 2
    GYRO_Y = 3
    GYRO_Z = 4
    MAG_X = 5
    MAG_Y = 6
    MAG_Z = 7
    SUN_STATUS = 8
    SUN_VEC_X = 9
    SUN_VEC_Y = 10
    SUN_VEC_Z = 11
    ECLIPSE = 12
    LIGHT_SENSOR_XP = 13
    LIGHT_SENSOR_XM = 14
    LIGHT_SENSOR_YP = 15
    LIGHT_SENSOR_YM = 16
    LIGHT_SENSOR_ZP1 = 17
    LIGHT_SENSOR_ZP2 = 18
    LIGHT_SENSOR_ZP3 = 19
    LIGHT_SENSOR_ZP4 = 20
    LIGHT_SENSOR_ZM = 21
    XP_COIL_STATUS = 22
    XM_COIL_STATUS = 23
    YP_COIL_STATUS = 24
    YM_COIL_STATUS = 25
    ZP_COIL_STATUS = 26
    ZM_COIL_STATUS = 27
    COARSE_ATTITUDE_QW = 28
    COARSE_ATTITUDE_QX = 29
    COARSE_ATTITUDE_QY = 30
    COARSE_ATTITUDE_QZ = 31
    STAR_TRACKER_STATUS = 32
    STAR_TRACKER_ATTITUDE_QW = 33
    STAR_TRACKER_ATTITUDE_QX = 34
    STAR_TRACKER_ATTITUDE_QY = 35
    STAR_TRACKER_ATTITUDE_QZ = 36


class IMU_IDX:
    TIME_IMU = 0
    ACCEL_X = 1
    ACCEL_Y = 2
    ACCEL_Z = 3
    MAGNETOMETER_X = 4
    MAGNETOMETER_Y = 5
    MAGNETOMETER_Z = 6
    GYROSCOPE_X = 7
    GYROSCOPE_Y = 8
    GYROSCOPE_Z = 9


class GPS_IDX:
    TIME_GPS = 0
    GPS_MESSAGE_ID = 1
    GPS_FIX_MODE = 2
    GPS_NUMBER_OF_SV = 3
    GPS_GNSS_WEEK = 4
    GPS_GNSS_TOW = 5
    GPS_LATITUDE = 6
    GPS_LONGITUDE = 7
    GPS_ELLIPSOID_ALT = 8
    GPS_MEAN_SEA_LVL_ALT = 9
    GPS_GDOP = 10
    GPS_PDOP = 11
    GPS_HDOP = 12
    GPS_VDOP = 13
    GPS_TDOP = 14
    GPS_ECEF_X = 15
    GPS_ECEF_Y = 16
    GPS_ECEF_Z = 17
    GPS_ECEF_VX = 18
    GPS_ECEF_VY = 19
    GPS_ECEF_VZ = 20


class THERMAL_IDX:
    TIME_THERMAL = 0
    IMU_TEMPERATURE = 1
    CPU_TEMPERATURE = 2
    BATTERY_PACK_TEMPERATURE = 3


class PAYLOAD_IDX:
    pass
